"""multiple schmea changes

Revision ID: 21869812b518
Revises: 7a2895b83f04
Create Date: 2024-08-23 08:38:11.300247

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '21869812b518'
down_revision = '7a2895b83f04'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('patients')
    with op.batch_alter_table('appointments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('date_time', sa.DateTime(), nullable=False))
        batch_op.add_column(sa.Column('user_id', sa.Integer(), nullable=False))
        batch_op.drop_constraint('appointments_patient_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'users', ['user_id'], ['id'])
        batch_op.drop_column('date')
        batch_op.drop_column('time')
        batch_op.drop_column('patient_id')

    with op.batch_alter_table('prescription', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', sa.Integer(), nullable=False))
        batch_op.drop_constraint('prescription_patient_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'users', ['user_id'], ['id'])
        batch_op.drop_column('patient_id')

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('no_of_pets',
               existing_type=sa.INTEGER(),
               nullable=False)

    with op.batch_alter_table('vets', schema=None) as batch_op:
        batch_op.alter_column('user_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('vets', schema=None) as batch_op:
        batch_op.alter_column('user_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('no_of_pets',
               existing_type=sa.INTEGER(),
               nullable=True)

    with op.batch_alter_table('prescription', schema=None) as batch_op:
        batch_op.add_column(sa.Column('patient_id', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('prescription_patient_id_fkey', 'patients', ['patient_id'], ['id'])
        batch_op.drop_column('user_id')

    with op.batch_alter_table('appointments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('patient_id', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('time', postgresql.TIME(), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('date', sa.DATE(), autoincrement=False, nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('appointments_patient_id_fkey', 'patients', ['patient_id'], ['id'])
        batch_op.drop_column('user_id')
        batch_op.drop_column('date_time')

    op.create_table('patients',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('no_of_pets', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('hospital_name', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('tags', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('medications', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('blood_pressure', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='patients_user_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='patients_pkey')
    )
    # ### end Alembic commands ###
