"""empty message

Revision ID: 319313fe5b7b
Revises: 777baa1988ec
Create Date: 2024-08-02 13:50:59.439659

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '319313fe5b7b'
down_revision = '777baa1988ec'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('password_hash',
               existing_type=sa.VARCHAR(length=80),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('password_hash',
               existing_type=sa.VARCHAR(length=80),
               nullable=True)

    # ### end Alembic commands ###
