"""empty message

Revision ID: 52a3b5896a21
Revises: f31e6dcdb426
Create Date: 2024-07-28 15:41:55.783451

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '52a3b5896a21'
down_revision = 'f31e6dcdb426'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('prescription', schema=None) as batch_op:
        batch_op.alter_column('patient_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.drop_constraint('prescription_patient_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'patients', ['patient_id'], ['id'])

    with op.batch_alter_table('vets', schema=None) as batch_op:
        batch_op.drop_constraint('vets_user_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'users', ['user_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('vets', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('vets_user_id_fkey', 'users', ['user_id'], ['id'], onupdate='CASCADE', ondelete='CASCADE')

    with op.batch_alter_table('prescription', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('prescription_patient_id_fkey', 'patients', ['patient_id'], ['id'], onupdate='CASCADE', ondelete='CASCADE')
        batch_op.alter_column('patient_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###
