"""empty message

Revision ID: 59485bf4ab44
Revises: 7dca392fc5ff
Create Date: 2024-07-07 17:01:45.710831

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '59485bf4ab44'
down_revision = '7dca392fc5ff'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('prescription', schema=None) as batch_op:
        batch_op.add_column(sa.Column('prescription_id', sa.Integer(), nullable=False))
        batch_op.drop_column('id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('prescription', schema=None) as batch_op:
        batch_op.add_column(sa.Column('id', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.drop_column('prescription_id')

    # ### end Alembic commands ###
