"""empty message

Revision ID: 70be35608a59
Revises: 59485bf4ab44
Create Date: 2024-07-07 17:08:04.181561

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '70be35608a59'
down_revision = '59485bf4ab44'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('prescription', schema=None) as batch_op:
        batch_op.add_column(sa.Column('id', sa.Integer(), autoincrement=True, nullable=False))
        batch_op.drop_column('prescription_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('prescription', schema=None) as batch_op:
        batch_op.add_column(sa.Column('prescription_id', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.drop_column('id')

    # ### end Alembic commands ###
