"""empty message

Revision ID: 7dca392fc5ff
Revises: dbf76204046a
Create Date: 2024-07-07 16:58:26.281301

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7dca392fc5ff'
down_revision = 'dbf76204046a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('prescription', schema=None) as batch_op:
        batch_op.add_column(sa.Column('id', sa.Integer(), nullable=False))
        batch_op.alter_column('med_2',
               existing_type=sa.VARCHAR(),
               nullable=True)
        batch_op.alter_column('test_1',
               existing_type=sa.VARCHAR(),
               nullable=True)
        batch_op.alter_column('test_2',
               existing_type=sa.VARCHAR(),
               nullable=True)

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_constraint('users_id_key', type_='unique')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_unique_constraint('users_id_key', ['id'])

    with op.batch_alter_table('prescription', schema=None) as batch_op:
        batch_op.alter_column('test_2',
               existing_type=sa.VARCHAR(),
               nullable=False)
        batch_op.alter_column('test_1',
               existing_type=sa.VARCHAR(),
               nullable=False)
        batch_op.alter_column('med_2',
               existing_type=sa.VARCHAR(),
               nullable=False)
        batch_op.drop_column('id')

    # ### end Alembic commands ###
