"""Meeting class to track meetings

Revision ID: d6aba232eb2a
Revises: e87c816bed40
Create Date: 2024-09-20 16:36:38.564712

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'd6aba232eb2a'
down_revision = 'e87c816bed40'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('transaction')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('transaction',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('tran_id', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('amount', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('status', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('customer_name', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('customer_email', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('timestamp', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='transaction_pkey'),
    sa.UniqueConstraint('tran_id', name='transaction_tran_id_key')
    )
    # ### end Alembic commands ###
