"""added room_id to Appointment for jitsi

Revision ID: e87c816bed40
Revises: 03c8429e7c01
Create Date: 2024-09-20 16:17:14.024964

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e87c816bed40'
down_revision = '03c8429e7c01'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('appointments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('room_id', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('appointments', schema=None) as batch_op:
        batch_op.drop_column('room_id')

    # ### end Alembic commands ###
