"""added availability.time_start, availability.time_end

Revision ID: 575b8f1b0db2
Revises: 4aa2efe621db
Create Date: 2024-09-02 15:47:26.647291

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '575b8f1b0db2'
down_revision = '4aa2efe621db'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('availability', schema=None) as batch_op:
        batch_op.add_column(sa.Column('time_start', sa.Time(), nullable=False))
        batch_op.add_column(sa.Column('time_end', sa.Time(), nullable=False))
        batch_op.drop_column('time')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('availability', schema=None) as batch_op:
        batch_op.add_column(sa.Column('time', postgresql.TIME(), autoincrement=False, nullable=False))
        batch_op.drop_column('time_end')
        batch_op.drop_column('time_start')

    # ### end Alembic commands ###
